[package]
name = "vault"
version = "0.3.0"
edition = "2021"

[features]
serde = ["dep:serde"]
tokio = ["dep:tokio"]

[dependencies]
rusqlite = "0.30.0"
serde = { version = "1.0.193", optional = true }
tokio = { version = "1.35.1", features = ["sync"], optional = true }
