[package]
name = "vault"
version = "0.5.0"
edition = "2021"

[features]
serde = ["dep:serde"]
tokio = ["dep:tokio"]

[dependencies]
rusqlite = "0.33.0"
serde = { version = "1.0.209", optional = true }
tokio = { version = "1.40.0", features = ["sync"], optional = true }
