[package]
name = "vault"
version = "0.2.0"
edition = "2021"

[features]
serde = ["dep:serde"]
tokio = ["dep:tokio"]

[dependencies]
rusqlite = "0.29.0"
serde = { version = "1.0.163", optional = true }
tokio = { version = "1.28.1", features = ["sync"], optional = true }
